### 练习题 1：数组创建与属性查看

**题目：** 使用 `arange()` 函数创建一个从 1 到 12 的一维等差数组，然后使用 `reshape()` 方法将其重塑为 3行4列的二维数组 。请分别打印出该数组的维度（`ndim`）、形状（`shape`）和元素总个数（`size`）。  

Python

```
import numpy as np

# 你的代码：
```

In [9]:
import numpy as np
#numpy 科学计算与数值运算的基础核心库

#arr:array 数组
#np.arange(起始值(选填,默认0),结束值(必填,不包含),步长(选填,默认1))
#->生成一个包含等差数列的一维数组
arr=np.arange(1,13)
arr1=arr.reshape(3,4)
print("数组为：")
print(arr1)
#ndim->数组的轴数
print("\n" f"维度：{arr1.ndim}")
print("\n" f"形状：{arr1.shape}")
print("\n" f"总个数：{arr1.size}")

数组为：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

维度：2

形状：(3, 4)

总个数：12


### 练习题 2：数据类型转换



**题目：** 创建一个包含浮点数 `[1.5, 2.6, 3.7, 4.8]` 的 NumPy 数组。使用 `astype()` 方法将该数组的数据类型转换为 32位整数 (`np.int32`)，并打印转换前后的数组及其数据类型名称 (`dtype.name`) 。  



Python

```
import numpy as np

# 你的代码：
```



In [2]:
import numpy as np
arr=np.array([1.5,2.6,3.7,4.8])
#.dtype->查看数组中元素的数据类型,返回的是一个对象
#.name->提取对象里的字符串名称
print(f"转换前数组：{arr};数据类型：{arr.dtype.name}")
#.astype->NumPy中用于转换数据类型的方法
#浮点数—>整数，直接舍去
arr_int32=arr.astype(np.int32)
print(f"转换后数组：{arr_int32};数据类型：{arr_int32.dtype.name}")

转换前数组：[1.5 2.6 3.7 4.8];数据类型：float64
转换后数组：[1 2 3 4];数据类型：int32


### 练习题 3：二维数组的切片操作



**题目：** 创建一个二维数组 `arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])`。请使用切片操作获取原数组的前两行，以及第 2 到第 3 列的子数组（即期望得到 `[[2, 3], [6, 7]]`）。  



Python

```
import numpy as np

# 你的代码：
```



In [3]:
import numpy as np
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
#前闭后开
#行索引[0:2]->0:第一行，1：第二行
#列索引[1:3]->1:第二列，2：第三列
arr1=arr[0:2,1:3]
print(f"切片操作后：\n{arr1}")

切片操作后：
[[2 3]
 [6 7]]


### 练习题 4：花式索引与布尔索引

**题目：** 给定一维数组 `arr = np.array([10, 15, 20, 25, 30, 35])`。

1. 使用花式索引提取第 1、3、5 个元素（即索引为 0, 2, 4 的元素）。  

   

   

2. 使用布尔索引提取数组中所有大于 20 的元素 。  

   

   

Python

```
import numpy as np

# 你的代码：
```



In [17]:
import numpy as np
arr=np.array([10,15,20,25,30,35])
#arr[]->从数组中提取数据
#花式索引->需要把想提取的索引位置打包成列表放入arr[……]
fancy_index=arr[[0,2,4]]
print(f"花式索引：{fancy_index}")
bool_index=arr[arr>20]
print(f"布尔索引：{bool_index}")
#arr>20:对数组中元素进行判断得到：[False, False, False, True, True, True]，保留True

花式索引：[10 20 30]
布尔索引：[25 30 35]


### 练习题 5：数组运算与广播机制



**题目：** 创建一个形状为 `(3, 4)` 的全 0 数组（使用 `zeros()` 函数）和一个一维数组 `arr_b = np.array([1, 2, 3, 4])` 。利用 NumPy 的广播机制，将这两个数组相加并打印出结果 。  



Python

```
import numpy as np

# 你的代码：
```



In [19]:
import numpy as np
arr_a=np.zeros((3,4))
arr_b=np.array([1,2,3,4])
result=arr_a+arr_b
print(result)
#广播机制：在形状不完全相同的数组之间进行算术运算

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


### 练习题 6：通用函数的应用

**题目：** 给定数组 `x = np.array([1, 4, 9, 16])` 和 `y = np.array([2, 1, 4, 5])`。

1. 使用一元通用函数 `np.sqrt()` 计算数组 `x` 中每个元素的平方根 。  

   

   

2. 将得到的平方根数组与数组 `y` 结合，使用二元通用函数 `np.maximum()` 找出对应位置上的最大值 。  

   

   

Python

```
import numpy as np

# 你的代码：
```



In [2]:
import numpy as np
x=np.array([1,4,9,16])
y=np.array([2,1,4,5])
x1=np.sqrt(x)
print("1.")
print(x1)
#np.maximum->逐元素比较，返回一个数组
max_x1_y=np.maximum(x1,y)
print("\n2.")
print(max_x1_y)

1.
[1. 2. 3. 4.]

2.
[2. 2. 4. 5.]


### 练习题 7：数组的转置



**题目：** 创建一个形状为 `(2, 3, 4)` 的三维数组 `arr = np.arange(24).reshape((2, 3, 4))` 。使用 `transpose()` 方法将该数组的轴顺序转换为 `(1, 0, 2)`，并打印转换后新数组的形状（`shape`） 。  



Python

```
import numpy as np

# 你的代码：
```



In [3]:
import numpy as np
arr=np.arange(24).reshape((2,3,4))#24->0~23
transpose=arr.transpose((1,0,2))
#0,1,2->1,0,2;2,3,4->3,2,4
print(f"新数组形状：{transpose.shape}")

新数组形状：(3, 2, 4)


### 练习题 8：条件逻辑运算



**题目：** 给出两个一维数组 `arr_x = np.array([1, 5, 7])`，`arr_y = np.array([2, 6, 8])` 以及一个布尔条件数组 `arr_con = np.array([True, False, True])` 。请使用 `np.where()` 函数，当条件为 `True` 时取 `arr_x` 中的对应元素，当条件为 `False` 时取 `arr_y` 中的对应元素 。  



Python

```
import numpy as np

# 你的代码：
```



In [4]:
import numpy as np
arr_x=np.array([1,5,7])
arr_y=np.array([2,6,8])
arr_con=np.array([True,False,True])
#np.where(条件，真值数组，假值数组)
result=np.where(arr_con,arr_x,arr_y)
print(result)

[1 6 7]


### 练习题 9：统计运算与排序



**题目：** 创建二维数组 `arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])` 。  



1. 使用统计方法计算该数组所有元素的算术平均值（`mean()`）。  

   

   

2. 使用 `sort()` 方法对该数组沿着 `axis=0` 的方向（按列顺序从小到大）进行排序，并打印排序后的结果 。  

   

   

Python

```
import numpy as np

# 你的代码：
```



In [5]:
import numpy as np
arr=np.array([
    [6,2,7],
    [3,6,2],
    [4,3,2]
])
mean=arr.mean()
print(f"算术平均值：{mean}")
arr.sort(axis=0)
mean1=arr.mean(axis=0)
print(mean1)
#axis=0->沿第0轴操作，即按列从小到大排序
#axis=1->沿第1轴操作，即按行从小到大排序
print(f"\n 按列顺序从小到大：\n{arr}")
#arr[行切片,列切片]
#arr[::-1,:] 上下翻转
#arr[:,::-1] 左右颠倒
#arr[::-1,::-1] 行列颠倒

算术平均值：3.888888888888889
[4.33333333 3.66666667 3.66666667]

 按列顺序从小到大：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


### 练习题 10：随机数生成与矩阵点积



**题目：** 1. 设置随机数种子为 `10`（使用 `np.random.seed()` 保证每次生成的随机数一致）。 2. 使用随机数模块生成两个形状为 `(2, 2)` 且服从 [0, 1) 均匀分布的随机矩阵 A 和 B（使用 `np.random.rand()`）。 3. 使用线性代数模块的 `dot()` 方法计算矩阵 A 和矩阵 B 的点积 。  



Python

```
import numpy as np

# 你的代码：
```

In [2]:
import numpy as np
#np.set_printoptions(precision=2（保留2位小数）, suppress=False（关闭科学计数法）)
np.random.seed(10)
#np.random.rand->返回[0,1)区间
#[0,15)->()*10+5
A=np.random.rand(2,2)
B=np.random.rand(2,2)
C=np.dot(A,B)
print(f"矩阵A：\n{A}")
print(f"矩阵B：\n{B}")
print(f"点积结果：\n{C}")

矩阵A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
点积结果：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
